declare module '*.css';
declare module '*.gif';
declare module '*.html';
declare module '*.ico';
declare module '*.jpg';
declare module '*.js';
declare module '*.png';
declare module '*.svg';
declare module '*.webp';
