name: CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Intall
        run: npm i
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  publish:
    if: ${{ github.actor == 'tkeron' }}
    needs: [test]
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Intall
        run: npm i
      - name: Build
        run: npm run build
      - name: cicd command
        run: npm run cicd
      - run: rm -rf src dist/test front web .github
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
