name: commands package
on:
  push:
    branches: 
      - master
    paths:
      - 'commands/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org/"
          
      - name: test and publish
        run: |
          cd commands
          npm i
          npm run build
          npm test
          rm -rf src dist/*.test.js .github coverage
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}

